using _403_Project1_StarWars.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _403_Project1_StarWars.Controllers
{
    public class Movies_SeenController : Controller
    {
        //this will be the list of seen movies by the user
        public static List<SeenMovies> lstMovies = new List<SeenMovies>();

        // GET: Movies_Seen
        public ActionResult DisplayMovies()
        {
            return View(lstMovies);
        }



        [HttpGet] //this is the add movie get method
        public ActionResult AddMovie()
        {
            return View();
        }

        [HttpPost] //this is the add movie post method which checks if the info is valid before adding
        public ActionResult AddMovie(SeenMovies myMovies)
        {
            myMovies.MovieID = lstMovies.Count() + 1; //the autogenerated movie ID
            if (ModelState.IsValid)
            {
                lstMovies.Add(myMovies);
                return RedirectToAction("DisplayMovies");
            }
            else
            {
                return View(myMovies);
            }
        }

        //these are the get and post EditMovie methods
        [HttpGet]
        public ActionResult EditMovie(int movieCode)
        {
            SeenMovies oMovies = lstMovies.Find(x => x.MovieID == movieCode);

            return View(oMovies);
        }

        [HttpPost]
        public ActionResult EditMovie(SeenMovies myModel) //THIS CURRENTLY DOESN'T SAVE EDITS
        {
            var obj = lstMovies.FirstOrDefault(x => x.MovieID == myModel.MovieID);
            if (obj != null)
            {
                obj.MovieTitle = myModel.MovieTitle;
                obj.MovieType = myModel.MovieType;
            }

            return View("DisplayMovies", lstMovies);
        }
    }
}
